{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  target:
    name: {{ .Values.externalSecret.targetName }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.deletionPolicy }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        decodingStrategy: {{ .decodingStrategy }}
    {{- end }}
{{- end }}
